### ISSUE TITLE
Does not check for current window position/size

### ISSUE THREAD

**Issue by minimum91** [w0lfschild/fullscreenER#1]
Hi there!
I'm extremely glad this exists at all, helps a lot, but I noticed one miss in the functionality - it's more like a toggle size X and size Y. It does not check if the current window has been resized. For example I put the window to fullscreen, but at some point I moved it or resized it manually and when I click the zoom button, instead of going fullscreen again, it resizes it to the window parameters that were before I clicked the zoom button in the first place? Feature or a bug?

**Comment by minimum91** [comment]
Quick video I made to illustrate the behavioural differences. 
http://cl.ly/0b20400H3O22

**Comment by w0lfschild** [comment]
@minimum91 sorry for taking so long to reply. It's not a bug but the functionality can be changed pretty easily.

**Comment by minimum91** [comment]
@w0lfschild No problem man, I understand it's a free time project :)
Can you give me a hint? I have no knowledge in programming, but I'm trying to claw my way in.
I would also like to remove the function that allows to resize all cocoa windows since that oddly conflicts with Photoshop.

**Comment by minimum91** [comment]
http://cl.ly/1m2L0l3u1f2g With a little help from my friends 🎱

**Comment by w0lfschild** [comment]
Glad you were able to adjust things to your liking.
