### ISSUE TITLE
J. River Media Center incompatible with FullscreenER

### ISSUE THREAD

**Issue by ahaghgoo** [w0lfschild/fullscreenER#2]
I'm using J. River Media Center to manage my media library.  A 30-day demo of the app can be [downloaded here](http://yabb.jriver.com/interact/index.php?board=45.0).  Because of how the app was developed, namely that it's essentially ported from Windows, it doesn't have a native Mac UI, specifically full screen support.  

So I was glad that I saw that your project on GitHub.  Unfortunately, when invoking Full Screen, which I had to enable through Quicksilver (I'll explain how in a moment), it made the J. River Media Center go berserk; it caused the system to go through an indefinite loop of creating another "Space" for the app to go full screen.  I'm wondering if you might know why the Mac OS kept indefinitely opening another Desktop Space?  The indefinite opening of additional Spaces came to a halt by either force quitting the app which was tricky because it made my system unresponsive, or it crashed and the application was closed because of the crash. 

Now if you want to experiment this on your own, here's the way to invoke "Enter Full Screen" mode in MC:
1. Download [Quicksilver](https://qsapp.com).
2. Go into QS's Preferences;
3. Go to Triggers;
4. Hit the "+" button at the bottom of the window to create a custom trigger;
5. Select "Keyboard";
6. In the first pane type "current application" then hit tab when "current application" shows up;
7. In the second pane type "show menu" until it too shows up as the selection then hit enter;
8. A hotkey is needed to trigger the trigger just created: to do so use the cursor and hit the empty space in the "Trigger" column.
9. In the sidebar that opens the shortcut box will be highlighted.  I've used "cmd+enter" as my shortcut, but yours could be anything. 

Once that is setup, the QS proxy command could be used on any app.  But this is meant to be used to show an issue between fullscreenER and J. River Media Center. 

So once the SIMBL file has been properly installed and the QS command is set up, I opened MC and invoked QS's proxy command to show MC's menu items, which there are only four, one being "Enter Full Screen."  What happens next is MC goes into Full Screen mode, but it becomes unresponsive and the MacOS perpetually creates a new space for MC to go into Full Screen mode.  The only way to stop it is to either force quit MC or let MC crash on its own.

Now I'm wondering why the app does this? What is making the OS/FullscreenER perpetually create a new space for J. River Media Center? 

I've crossposted this on the J. River's Media Center forum [here](http://yabb.jriver.com/interact/index.php?topic=104058.0).

Thanks for the consideration!
-A

**Comment by w0lfschild** [comment]
Not too sure. Sounds like it could be an issue with the way the app is made.

**Comment by w0lfschild** [comment]
The attached version will add the full screen option to the menubars first item (the bolded app name). I've tested it and it works.

[fullscreenER.bundle.zip](https://github.com/w0lfschild/fullscreenER/files/310598/fullscreenER.bundle.zip)
