### ISSUE TITLE
Prevents the launch of Amazon's "Send to Kindle" utility

### ISSUE THREAD

**Issue by Fofer** [w0lfschild/fullscreenER#3]
With fullscreenER enabled, Amazon's "[Send to Kindle](http://www.amazon.com/gp/sendtokindle/mac)" utility crashes immediately on launch. This is a consistent and 100% reproducible crash on my systems. With fullscreenER disabled, "Send to Kindle" launches fine.

**Comment by w0lfschild** [comment]
Not the best fix but https://github.com/w0lfschild/fullscreenER/commit/8f716d7a9a413a7dad5999aa52ae4451c5cae1b4

[Download](https://github.com/w0lfschild/fullscreenER/raw/master/build/fullscreenER.zip)
