### ISSUE TITLE
Interference with some status bar's icons

### ISSUE THREAD

**Issue by waxfingers** [w0lfschild/fullscreenER#4]
First off I want to thank you for all the incredible work you're doing to make OSX more tweakable and way cooler =)   
  
I've got a small issue with the fullscreenER plug, it interferes and displaces a couple of my system menu bar's icons: caffeine and Clipmenu. It's not just the visual annoyance, I still can acess Clipmenu dropdown dialog but caffeine is in lock down. If I miss and click on the double arrows above the whole system behaves erraticaly. That's it, attached a screengrab

Happy happy joy joy

![fullscreener_issue](https://cloud.githubusercontent.com/assets/13238340/21577470/6a0cb4ce-cf53-11e6-9b40-25d1949d8b05.jpg)

**Comment by w0lfschild** [comment]
Fixed.
