### ISSUE TITLE
FullscreenER no working on OSX 10.10

### ISSUE THREAD

**Issue by servusqwertz** [w0lfschild/fullscreenER#5]
Accoding to your README, FullscreenER is compatible with 10.10 upwards, but when loading via mySIMBL, Console.app states that the app was built for 10.11. I was just wondering if you dropped support for 10.10 (which would be a pity) or if this is indeed a bug? I used the latest version, downloaded either via mySIMBL or github.

I'm on OS X 10.10.5, with latest updates etc.

Cheers and thanks for the other great apps and SIMBL plugins,
Felix

Below a representative console output after loading fullscreenER and opening console.app:

> 16.01.17 14:00:00,849 Console[1409]: Error loading /Library/Application Support/SIMBL/Plugins/fullscreenER.bundle/Contents/MacOS/fullscreenER:  dlopen(/Library/Application Support/SIMBL/Plugins/fullscreenER.bundle/Contents/MacOS/fullscreenER, 265): Symbol not found: ___NSArray0__
>   Referenced from: /Library/Application Support/SIMBL/Plugins/fullscreenER.bundle/Contents/MacOS/fullscreenER (which was built for Mac OS X 10.11)
>   Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
>  in /Library/Application Support/SIMBL/Plugins/fullscreenER.bundle/Contents/MacOS/fullscreenER

**Comment by w0lfschild** [comment]
Is it actually not working or are you just seeing an error in console?

**Comment by servusqwertz** [comment]
It's actually not working. The Icon does not change and window goes fullscreen after click, not maximized.

And just to make sure, I reinstalled all components of mySIMBL (and fixed a problem concerning the fact that other mySIMBL plugins would not start after system (re)boot (don't know exactly what the problem was, but now both cosyTabs and Flashlight function as expected after (re)boot).)

Console error shows up every time I open a program (as I would expect).

Is there anything else you might need from me that would you pinpoint the problem?

cheers,
Felix

![fullscreener icons safari](https://cloud.githubusercontent.com/assets/25151885/22021521/23c6586c-dcbe-11e6-99fe-b186c2ae7c2f.png)

**Comment by w0lfschild** [comment]
Okay should be fixed in the latest build on [mySIMBL](https://github.com/w0lfschild/mySIMBL).

**Comment by servusqwertz** [comment]
yep, now it works! Brilliant!

cheers!
