### ISSUE TITLE
Dropbox and Airmail 3 conflict

### ISSUE THREAD

**Issue by veitch123** [w0lfschild/fullscreenER#6]
This is BRILLIANT. And thanks so much for writing it. It means I can finally, finally make After Effects fullscreen. The only problem I have is that Airmail 3 will occasionally freak out on me making infinite new spaces and Dropbox won't open.

**Comment by w0lfschild** [comment]
Hmm might be a good idea to just blacklist Dropbox in mySIMBL unless there's something you're needing to modify about DropBox.

If I get the time I'll try to look into this. Probably has to do with custom implementations of something.

**Comment by veitch123** [comment]
Amazing. I’ll just blacklist it! Will report back if it doesn’t work.
Thanks so much.

—
*Sent from my Apple Car*
veitch.me | @veitchtweets <https://twitter.com/veitchtweets>

On 7 January 2018 at 21:39:11, Wolfgang Baird (notifications@github.com)
wrote:

Hmm might be a good idea to just blacklist Dropbox in mySIMBL unless
there's something you're needing to modify about DropBox.

If I get the time I'll try to look into this. Probably has to do with
custom implementations of something.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/w0lfschild/fullscreenER/issues/6#issuecomment-355846739>,
or mute the thread
